controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/ImuSensorBroadcaster

    onnxruntime_controller:
      type: onnxruntime_controller/ONNXRuntimeController

onnxruntime_controller:
  ros__parameters:
    observation_interfaces:
      [
        "imu/angular_velocity",
        "imu/linear_acceleration",
        "linear.y",
        "position",
        "velocity",
        "last_action",
      ]
    observation_types:
      [
        "geometry_msgs/msg/Vector3",
        "geometry_msgs/msg/Vector3",
        "float64",
        "float64",
        "float64",
        "float64",
      ]
    observation_scales: [1.0, 1.0, 1.0, 1.0, 0.05, 1.0]
    actions_interface: "position"
    joint_names: ["a", "l"]
    action_scale: 0.25
    clip_actions: 100.0
    action_offsets: [0.0, 0.0]
    reference_interfaces: ["linear", "angular"]
    reference_types: ["geometry_msgs/msg/Vector3", "geometry_msgs/msg/Vector3"]

joint_state_broadcaster:
  ros__parameters:
    joints: ["a", "l"]
