controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    imu_sensor_broadcaster:
      type: "imu_sensor_broadcaster/IMUSensorBroadcaster"

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id: imu_link
