''' 
This ROS2 node loads a trained RL model using rsl-rl and publishes messages at regular intervals. 
It is subscribed to the 'obs' topic, which gathers and formats the observations for the model to act upon.
It publishes to the 'actions' topic, sending out the actions generated by the model based on the observations.
'''


import os

# ROS Imports
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32MultiArray

# RL Imports
import torch
import torch.nn as nn

class ActorNetwork(nn.Module):
    """Simple actor network for inference"""
    def __init__(self, input_dim, output_dim, hidden_dims, activation='elu'):
        super().__init__()
        
        # Choose activation function
        if activation == 'elu':
            act = nn.ELU()
        elif activation == 'relu':
            act = nn.ReLU()
        elif activation == 'tanh':
            act = nn.Tanh()
        else:
            act = nn.ELU()
        
        # Build the network layers
        layers = []
        prev_dim = input_dim
        for hidden_dim in hidden_dims:
            layers.append(nn.Linear(prev_dim, hidden_dim))
            layers.append(act)
            prev_dim = hidden_dim
        layers.append(nn.Linear(prev_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
    
    def forward(self, x):
        return self.network(x)

class Model():
    def __init__(self, modelfile='', *kwargs):
        # Load the saved checkpoint
        checkpoint = torch.load(modelfile, map_location='cpu')
        
        # Extract model state dict
        if isinstance(checkpoint, dict) and 'model_state_dict' in checkpoint:
            state_dict = checkpoint['model_state_dict']
        elif isinstance(checkpoint, dict):
            state_dict = checkpoint
        else:
            state_dict = checkpoint
        
        # Infer architecture from the state dict
        # Look at actor.0.weight shape to get input and first hidden dim
        num_actor_obs = state_dict['actor.0.weight'].shape[1]
        num_actions = state_dict['actor.6.weight'].shape[0]
        
        # Build hidden dims list from the state dict
        hidden_dims = []
        layer_idx = 0
        while f'actor.{layer_idx}.weight' in state_dict:
            hidden_dims.append(state_dict[f'actor.{layer_idx}.weight'].shape[0])
            layer_idx += 2  # Skip activation layers
        
        # Remove the last layer (output layer) from hidden_dims
        if hidden_dims:
            hidden_dims = hidden_dims[:-1]
        
        # Create the actor network
        self.actor = ActorNetwork(
            input_dim=num_actor_obs,
            output_dim=num_actions,
            hidden_dims=hidden_dims,
            activation='elu'
        )
        
        # Load only the actor weights
        actor_state_dict = {
            k.replace('actor.', 'network.'): v 
            for k, v in state_dict.items() 
            if k.startswith('actor.') and not k.startswith('actor_obs')
        }
        self.actor.load_state_dict(actor_state_dict)
        self.actor.eval()

        # Set up any other internal variables we might need
        self.name = str(modelfile).split()[-1]
        self.inputs = num_actor_obs
        self.outputs = num_actions

    def act(self, inputs):
        # given some set of inputs, return outputs generated by the model
        with torch.no_grad():
            actions = self.actor(torch.tensor(inputs, dtype=torch.float32))
            return actions.numpy()

    def __str__(self):
        print(f"""
            Trained Model: {self.name}
            size {self.inputs} --> {self.outputs}
              """)

class ModelPublisher(Node):

    def __init__(self, modelfile=''):
        super().__init__('model_publisher')
        self.publisher_ = self.create_publisher(Float32MultiArray, 'actions', 10)
        print("Publisher to 'actions' topic initialized.")
        self.subscriber_ = self.create_subscription(
            Float32MultiArray,
            'obs',
            self.listener_callback,
            10)
        print("Subscriber to 'obs' topic initialized.")
        self.model = Model(modelfile)  # specify the actual model file path
        print("Model loaded and publisher node initialized.")
        print("="*40)
        print("listening...")
    
    def listener_callback(self, msg):
        action = self.model.act(list(msg.data))
        action_msg = Float32MultiArray()
        action_msg.data = [float(x) for x in action]
        self.publisher_.publish(action_msg)


def load_config():
    import yaml
    config_path = os.environ.get('CATBOT_CONFIG', '/catbot-ros2/config/robot.yaml')
    workspace_dir = os.environ.get('CATBOT_WS', '/catbot-ros2')
    with open(config_path) as f:
        config = yaml.safe_load(f)
    return os.path.join(workspace_dir, config['model']['path'])


def main(args=None):
    rclpy.init(args=args)
    MODELPATH = load_config()
    print(f'Loading model from: {MODELPATH}')
    model_publisher = ModelPublisher(MODELPATH)

    rclpy.spin(model_publisher)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    model_publisher.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
